# Generated by Django 5.2.1 on 2025-06-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_solicitudretiro_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudretiro',
            name='tiempo_en_completar',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
